// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*executionPayloadEnvelopePragueMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (e ExecutionPayloadEnvelopePrague) MarshalJSON() ([]byte, error) {
	type ExecutionPayloadEnvelopePrague struct {
		ExecutionPayload *ExecutableData `json:"executionPayload"  gencodec:"required"`
		BlockValue       *hexutil.Big    `json:"blockValue"  gencodec:"required"`
		BlobsBundle      *BlobsBundleV1  `json:"blobsBundle"`
		Requests         [][]byte        `json:"executionRequests" gencodec:"required"`
		Override         bool            `json:"shouldOverrideBuilder"`
		Witness          *hexutil.Bytes  `json:"witness,omitempty"`
	}
	var enc ExecutionPayloadEnvelopePrague
	enc.ExecutionPayload = e.ExecutionPayload
	enc.BlockValue = (*hexutil.Big)(e.BlockValue)
	enc.BlobsBundle = e.BlobsBundle
	enc.Requests = e.Requests
	enc.Override = e.Override
	enc.Witness = e.Witness
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (e *ExecutionPayloadEnvelopePrague) UnmarshalJSON(input []byte) error {
	type ExecutionPayloadEnvelopePrague struct {
		ExecutionPayload *ExecutableData `json:"executionPayload"  gencodec:"required"`
		BlockValue       *hexutil.Big    `json:"blockValue"  gencodec:"required"`
		BlobsBundle      *BlobsBundleV1  `json:"blobsBundle"`
		Requests         [][]byte        `json:"executionRequests" gencodec:"required"`
		Override         *bool           `json:"shouldOverrideBuilder"`
		Witness          *hexutil.Bytes  `json:"witness,omitempty"`
	}
	var dec ExecutionPayloadEnvelopePrague
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ExecutionPayload == nil {
		return errors.New("missing required field 'executionPayload' for ExecutionPayloadEnvelopePrague")
	}
	e.ExecutionPayload = dec.ExecutionPayload
	if dec.BlockValue == nil {
		return errors.New("missing required field 'blockValue' for ExecutionPayloadEnvelopePrague")
	}
	e.BlockValue = (*big.Int)(dec.BlockValue)
	if dec.BlobsBundle != nil {
		e.BlobsBundle = dec.BlobsBundle
	}
	if dec.Requests == nil {
		return errors.New("missing required field 'executionRequests' for ExecutionPayloadEnvelopePrague")
	}
	e.Requests = dec.Requests
	if dec.Override != nil {
		e.Override = *dec.Override
	}
	if dec.Witness != nil {
		e.Witness = dec.Witness
	}
	return nil
}
